import Link from 'next/link';
import TalentNetworkForm from '@/components/TalentNetworkForm';

const industries = [
  ['01', '✦', 'Healthcare', 'Nursing, allied health, clinical support, and care coordination.'],
  ['02', '⌁', 'Education', 'Teachers, specialists, classroom support, and student services.'],
  ['03', '◎', 'Behavioral health', 'Counseling, case management, and community-based care.'],
  ['04', '↗', 'Business support', 'Operations, administration, customer experience, and project support.'],
];

export default function Home() {
  return <main>
    <section className="demo-hero"><img className="hero-photo" src="/s3-team-hero.png" alt="Healthcare, business, and education professionals walking together"/><div className="hero-shade"/><div className="shell hero-content"><p className="kicker gold">Talent moves everything forward</p><h1>Great people.<br/><em>Stronger teams.</em></h1><p className="hero-copy">We connect skilled professionals with organizations where their work makes a real difference.</p><div className="hero-actions"><Link className="demo-btn" href="/jobs">Explore opportunities <span>↗</span></Link><Link className="text-link light" href="/employers">I’m hiring →</Link></div></div><div className="hero-values"><div><strong>People-first</strong><span>Every placement starts with listening.</span></div><div><strong>Responsive</strong><span>Qualified talent when it matters.</span></div><div><strong>Specialized</strong><span>Focused expertise across essential fields.</span></div></div></section>
    <section className="job-search-section"><div className="shell job-search-grid"><div><p className="kicker blue">Your next move</p><h2>Find work that<br/><em>fits your life.</em></h2></div><form action="/jobs" className="search-grid"><label>What kind of role?<input name="q" placeholder="Title, skill, or keyword"/></label><label>Where?<input name="location" placeholder="City, state, or ZIP"/></label><label>Work style<select name="workplace" defaultValue=""><option value="">All opportunities</option><option>On-site</option><option>Hybrid</option><option>Remote</option></select></label><button className="search-button">Search roles <span>→</span></button></form></div></section>
    <section className="dual-path"><article className="path-card professional"><span className="giant-number">01</span><div><p className="kicker gold">For professionals</p><h2>Work with<br/>purpose.</h2><p>Tell us where you want to go. We’ll connect you with flexible opportunities aligned with your skills, goals, and schedule.</p><Link className="text-link light" href="#apply">Submit your résumé ↗</Link></div></article><article className="path-card employer"><span className="giant-number">02</span><div><p className="kicker gold">For employers</p><h2>Build the team<br/>you need.</h2><p>From one critical opening to an entire project team, S3 delivers thoughtful, responsive staffing tailored to your organization.</p><Link className="text-link light" href="/employers">Request talent ↗</Link></div></article></section>
    <section id="industries" className="industries-section"><div className="shell"><div className="section-intro"><div><p className="kicker blue">Specialized talent</p><h2>Expertise where<br/>it matters most.</h2></div><p>We focus on essential, people-centered fields where the right professional can change an outcome.</p></div><div className="industry-grid">{industries.map(([n,icon,title,copy]) => <article className="industry-card" key={title}><span className="card-number">{n}</span><span className="industry-icon">{icon}</span><h3>{title}</h3><p>{copy}</p><Link href={`/jobs?industry=${encodeURIComponent(title)}`}>Explore field →</Link></article>)}</div></div></section>
    <section id="about" className="standard-section"><div className="standard-mark"><p className="kicker dark">The S3 Standard</p><strong>3×</strong><p>Listen deeply.<br/>Move quickly.<br/>Follow through.</p></div><div className="standard-copy"><p className="kicker blue">More human by design</p><h2>Staffing should feel<br/><em>personal—not transactional.</em></h2><p>We built Superior Staffing Solutions around a simple belief: when professionals feel understood and employers feel supported, better matches happen. Our team stays close from first conversation through first day and beyond.</p><div className="check-grid"><span>✓ Dedicated support</span><span>✓ Carefully matched talent</span><span>✓ Clear communication</span><span>✓ Flexible workforce solutions</span></div></div></section>
    <section id="apply" className="apply-section"><div className="shell apply-grid"><div><p className="kicker blue">Let’s get started</p><h2>Your next<br/>opportunity<br/>could start here.</h2><p>Join the S3 talent network. Upload your résumé and tell us what kind of work you’re looking for.</p></div><TalentNetworkForm/></div></section>
  </main>;
}
